### ISSUE TITLE
Please add a method to place skulls in the world.

### ISSUE THREAD

**Issue by GetDerpy** [Deanveloper/SkullCreator#1]
As per PM on spigot.

Please add some kind of method to allow us to place the skulls in the world without player interaction. Something like SkullCreator.setSkullBlock(Block block, ItemStack skull);

**Comment by deanveloper** [comment]
Honestly I thought Bukkit would support some kind of ItemStack -> Block conversion. I'll check it out and hopefully make a solution that works for both 1.13 and pre-1.13 versions

**Comment by GetDerpy** [comment]
Same, I attempted several times to convert the ItemStack metadata to SkullMeta. Even the Skull class only takes a username to set the skin, there doesn't seem to be any way to apply the custom texture. I suspect some NMS trickery is going to be needed.

**Comment by deanveloper** [comment]
I think the way I'm going to set it is with... the default `/blockdata` and `/data` commands 😅 

It's really just a terrible solution, but so was using `Bukkit.getUnsafe()`, but it's the most version-compatible way to do it.

**Comment by espidev** [comment]
These don't work in other worlds...

**Comment by deanveloper** [comment]
Supported in 3.0.0
