### ISSUE TITLE
Version 3.3.0 did not exist

### ISSUE THREAD

**Issue by pybsh** [Deanveloper/SkullCreator#11]
![image](https://user-images.githubusercontent.com/59782214/109754775-fe7b6300-7c27-11eb-8afa-14645c97200c.png)
<br></br>
![image](https://user-images.githubusercontent.com/59782214/109754783-03401700-7c28-11eb-9f60-db7d3f243b01.png)

**Comment by deanveloper** [comment]
idk i've never used gradle. someone else contributed that to the readme. i've never heard of anyone having issues of using it with maven and (afaik) gradle should be compatible with maven, right?

by the looks of it, whoever made the contribution did not add the repository to the gradle instructions. you need to add `https://dl.bintray.com/deanveloper/SkullCreator` as a repository, however that's done in gradle

**Comment by deanveloper** [comment]
nvm i'm dumb and see that it's added in the instructions lol. i was confused by the `mavenCentral()` thing. can you show me what your build.gradle looks like?

**Comment by deanveloper** [comment]
nvm i'm dumb x2...

yea the newest version is 3.0.0... not sure why the build.gradle says 3.3.0. likely just a typo from the dude who added that which i didn't catch.

i changed the readme to show 3.0.0 for gradle

**Comment by rootpi-src** [comment]
That repositoriy doesn't have 3.3.0 version. Please edit 3.3.0 to 3.0.0. I already tested that only 3.0.0 is worked.
