### ISSUE TITLE
Default name from base64 is 'aaaaa'

### ISSUE THREAD

**Issue by GriffinCodes** [Deanveloper/SkullCreator#14]
Super minor detail, but surely [this](https://github.com/deanveloper/SkullCreator/blob/master/src/main/java/dev/dbassett/skullcreator/SkullCreator.java#L266) isn't intentional? A better default could be "Player" or something
![image](https://user-images.githubusercontent.com/12417961/116760906-3e6e8480-a9e4-11eb-95c0-276181760837.png)

It gave me a good laugh though :)

**Comment by deanveloper** [comment]
not intentional... LOL

yeah i’ll get this fixed
