### ISSUE TITLE
Bintray shut down 

### ISSUE THREAD

**Issue by GriffinCodes** [Deanveloper/SkullCreator#15]
One of our developers cannot compile the project due to bintray sunsetting their services

![Screenshot_20210502-212034_Chrome.jpg](https://user-images.githubusercontent.com/12417961/116836483-3e10ed80-ab8c-11eb-8bf2-1a85afe349d9.jpg)

We can move the project to our [own repo](https://paste.bnn.gg/epehe) while this is fixed, so no rush :)

**Comment by deanveloper** [comment]
ahhh i got an email about bintray shutting down... thought i had more time since i skimmed it. i’ll see what i can do!

**Comment by deanveloper** [comment]
i'll be using [this](https://github.com/github/maven-plugins#readme), woop woop

**Comment by deanveloper** [comment]
new maven url: `https://github.com/deanveloper/SkullCreator/raw/mvn-repo/`
