### ISSUE TITLE
Maven Installation Failure

### ISSUE THREAD

**Issue by Darrionat** [Deanveloper/SkullCreator#16]
I'm having an issue where Maven is unable to retrieve this dependency.

I added both of these to my pom.xml
`        <repository>
            <id>skullcreator-repo</id>
            <url>https://github.com/deanveloper/SkullCreator/raw/mvn-repo/</url>
        </repository>`
and 
`        <dependency>
            <groupId>dev.dbassett</groupId>
            <artifactId>skullcreator</artifactId>
            <version>3.0.1</version>
            <scope>compile</scope>
        </dependency>`
When running `mvn clean install`, it states that `[WARNING] The POM for dev.dbassett:skullcreator:jar:3.0.1 is missing, no dependency information available`

**Comment by deanveloper** [comment]
Can you provide the entire output of `mvn clean install`?

**Comment by deanveloper** [comment]
I am currently setting up a JFrog artifactory. This should allow me to have an actual maven repository rather than the hacky GitHub solution.

**Comment by Darrionat** [comment]
Apologies, I had a setting called `Work Offline` enabled on IntelliJ, meaning it was unable to download it. Thanks for your time.
