### ISSUE TITLE
Method "itemWithUuid" should be edited.

### ISSUE THREAD

**Issue by zedaster** [Deanveloper/SkullCreator#2]
Spigot API 1.12 haven`t setOwningPlayer()
![default](https://user-images.githubusercontent.com/23569079/44096139-0112eb28-9ff4-11e8-8991-ba0a85fbd7af.PNG)

**Comment by deanveloper** [comment]
Thanks for letting me know. For now, remove the UUID-based methods. I'll replace them when I have time. (Or if you're feeling particularly savvy, feel free to make a pull request)

**Comment by deanveloper** [comment]
I did not want to remove the methods, so I've added docs to specify that they only work in 1.13. I'll do some research later to see if there is a good solution for using UUIDs with skulls in <1.13 versions.

**Comment by deanveloper** [comment]
I am going to end support for 1.12 and earlier, this will only support 1.12.2 and later.
