### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by RRS-9747** [Deanveloper/SkullCreator#23]
Add a way to rename the skull from base64 pls

**Comment by deanveloper** [comment]
Can you not rename the item the same way you normally do?

**Comment by RRS-9747** [comment]
I can but I have 243 itemstack. so it will be easy for me if you add renaming with API

**Comment by deanveloper** [comment]
Yeah I'd recommend just making a method that changes the skull with SkullCreator and then uses ItemMeta to rename the skull. No need to add even more methods to SkullCreator.
