### ISSUE TITLE
Issue with different worlds

### ISSUE THREAD

**Issue by Cristichi** [Deanveloper/SkullCreator#3]
It seems the position where it tries to merge the block data is taken from the main world instead of the world where the block is located.

Besides that, great work. This could save my life!

**Comment by deanveloper** [comment]
Unfortunately the only way to place blocks with my current system is using the `data` command, which from the console command sender doesn't work well. I'll see what I can do (perhaps a custom `CommandSender`?) to make it work properly.

**Comment by Cristichi** [comment]
Thanks a lot!

**Comment by deanveloper** [comment]
Supported in 3.0.0
