### ISSUE TITLE
Javadocs

### ISSUE THREAD

**Issue by Laarryy** [Deanveloper/SkullCreator#7]
Hello! Just wanted to let you know, though you probably already do, that the Javadocs aren't loading (GitHub gives a 404) and I can't seem to download them from the maven repo directly either. I see they're here, so I'll give them a try but I just thought you might wanna know! :)

Thanks!

**Comment by deanveloper** [comment]
working on fixing it now, thanks for the heads up!

**Comment by deanveloper** [comment]
aaand fixed! https://skullcreator.dbassett.dev/dev/dbassett/skullcreator/SkullCreator.html
