### ISSUE TITLE
Skull Rotation/Placement

### ISSUE THREAD

**Issue by olliestanley** [Deanveloper/SkullCreator#8]
Hi, just wondering if you know how to make a skull not float when it's created by SkullCreator. I have changed the rotation by using

`((Skull) block.getState()).setRotation`

But the skull always floats a little rather than being placed directly on the block below. I also cannot see how to set whether a skull is wall-mounted. It seems not to be possible through anything in the Bukkit API. Any help would be greatly appreciated!

**Comment by deanveloper** [comment]
What version are you running?

**Comment by olliestanley** [comment]
@deanveloper I'm on 1.12.2 right now

**Comment by deanveloper** [comment]
okay after doing some testing, i've literally never seen this behavior before LOL. using Skull#setRotation in 1.12.2, they are all mounted on the south wall (facing north), but are facing different directions. (EDIT - i'll get you an answer for a fix soon, just gimme a bit)
![image](https://user-images.githubusercontent.com/3196327/91563579-bab84180-e904-11ea-9779-223855119c0f.png)

**Comment by olliestanley** [comment]
@deanveloper So for you they're spawning as if wall-mounted even without a wall to be mounted on?

**Comment by deanveloper** [comment]
Yes, essentially. Anyway according to the Minecraft Wiki, this is how it'd be done: 
![image](https://user-images.githubusercontent.com/3196327/91564582-7037c480-e906-11ea-9f95-6e05421a3623.png)

So essentially, you'd do `state.setRawData((byte) 1)`, then do `state.setRotation(blockFace)`
A quick demo to generate all of the rotations:
```java
Block _temp = b;
for (BlockFace face : BlockFace.values()) {
	switch (face) {
		case UP:
		case DOWN:
		case SELF:
			continue;
	}

	SkullCreator.blockWithBase64(_temp, TEST_SKULL);
	Skull s = (Skull) _temp.getState();
	s.setRawData((byte) 1);
	s.setRotation(face);
	s.update();

	_temp = _temp.getRelative(BlockFace.WEST);
}
```
![image](https://user-images.githubusercontent.com/3196327/91564997-1daad800-e907-11ea-95fe-93ee7ec7f6eb.png)

You can generate the wall-mounted heads by doing `state.setRawData(byteValue)` and not doing anything with `state.setFacing`.

**Comment by olliestanley** [comment]
Okay I'll try that. I previously tried

                    SkullCreator.blockWithBase64(block, b64);
                    Skull skull = (Skull) block.getState();
                    skull.setRotation(rotation);
                    skull.setRawData((byte) 1);
                    skull.update();

But perhaps setting the rotation before the raw data caused it to fail. Thanks for the help!

**Comment by deanveloper** [comment]
No problem!
